[package]
name = "dsfun"
version = "0.1.0"
authors = ["Max Riveiro <kavu13@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
publish = false

[dependencies]
clap = "2"
failure = "0.1"
failure_derive = "0.1"
